modifexeptions = 
{
	modifier_abaddon_frostmourne = 1,
	modifier_abaddon_borrowed_time_passive = 1,
	modifier_alchemist_goblins_greed = 1,
	modifier_antimage_mana_break = 1,
	modifier_antimage_spell_shield = 1,
	modifier_axe_counter_helix = 1,
	modifier_beastmaster_inner_beast = 1,
	modifier_bloodseeker_thirst = 1,
	modifier_bounty_hunter_jinada = 1,
	modifier_brewmaster_drunken_brawler = 1,
	modifier_bristleback_bristleback = 1,
	modifier_bristleback_warpath = 1,
	modifier_broodmother_incapacitating_bite = 1,
	modifier_centaur_return = 1,
	modifier_chaos_knight_chaos_strike = 1,
	modifier_crystal_maiden_brilliance_aura = 1,
	modifier_dragon_knight_dragon_blood = 1,
	modifier_drow_ranger_trueshot = 1,
	modifier_drow_ranger_marksmanship = 1,
	modifier_earthshaker_aftershock = 1,
	modifier_enchantress_untouchable = 1,
	modifier_faceless_void_time_lock = 1,
	modifier_huskar_berserkers_blood = 1,
	modifier_juggernaut_blade_dance = 1,
	modifier_legion_commander_moment_of_courage = 1,
	modifier_life_stealer_feast = 1,
	modifier_lina_fiery_soul = 1,
	modifier_luna_moon_glaive = 1,
	modifier_luna_lunar_blessing = 1,
	modifier_lycan_feral_impulse = 1,
	modifier_meepo_self_geostrike = 1,
	modifier_meepo_divided_we_stand = 1,
	modifier_necrolyte_sadist_active = 1,
	modifier_necrolyte_heartstopper_aura = 1,
	modifier_night_stalker_hunter_in_the_night = 1,
	modifier_greevil_miniboss_white_degen_aura = 1,
	modifier_obsidian_destroyer_essence_aura = 1,
	modifier_phantom_assassin_blur = 1,
	modifier_phantom_assassin_coupdegrace = 1,
	modifier_phantom_lancer_juxtapose = 1,
	modifier_phantom_lancer_phantom_edge = 1,
	modifier_pudge_flesh_heap = 1,
	modifier_razor_unstable_current = 1,
	modifier_riki_permanent_invisibility = 1,
	modifier_rubick_null_field = 1,
	modifier_sand_king_caustic_finale = 1,
	modifier_nevermore_necromastery = 1,
	modifier_nevermore_presence = 1,
	modifier_slardar_bash = 1,
	modifier_slark_essence_shift = 1,
	modifier_slark_shadow_dance_passive = 1,
	modifier_slark_shadow_dance_passive_regen = 1,
	modifier_slark_shadow_dance = 1,
	modifier_sniper_headshot = 1,
	modifier_sniper_take_aim = 1,
	modifier_spectre_desolate = 1,
	modifier_spectre_dispersion = 1,
	modifier_spirit_breaker_empowering_haste = 1,
	modifier_spirit_breaker_greater_bash = 1,
	modifier_storm_spirit_overload_passive = 1,
	modifier_storm_spirit_overload = 1,
	modifier_sven_great_cleave = 1,
	modifier_templar_assassin_psi_blades = 1,
	modifier_tidehunter_kraken_shell = 1,
	modifier_shredder_reactive_armor = 1,
	modifier_tiny_craggy_exterior = 1,
	modifier_tiny_grow = 1,
	modifier_troll_warlord_fervor = 1,
	modifier_ursa_fury_swipes = 1,
	modifier_vengefulspirit_command_aura = 1,
	modifier_venomancer_poison_sting = 1,
	modifier_viper_nethertoxin = 1,
	modifier_viper_corrosive_skin = 1,
	modifier_visage_gravekeepers_cloak = 1,
	modifier_weaver_geminate_attack = 1,
	modifier_skeleton_king_vampiric_aura = 1,
	modifier_skeleton_king_mortal_strike = 1,
	modifier_skeleton_king_reincarnation = 1,
	modifier_skeleton_king_reincarnation_scepter = 1,
	modifier_skeleton_king_reincarnation_scepter_active = 1,
	modifier_zuus_static_field = 1,
	modifier_spectre_spectral_dagger_in_path = 1,
	modifier_spectre_spectral_dagger_path_phased = 1,
	modifier_spectre_spectral_dagger_path = 1,
	modifier_fountain_aura_custom = 1,
	modifier_item_bow = 1,
	

}--Huskar spear
--monkey jingu
--elder natural order
--kotl ult
--ogre multicast
--slark ulti
--storm overload
--ursa swipes
--dk ulti
--lucan ulti
--zombie ulti